print("coloque o numero 1")
x=(input())
print("coloque o numero 2")
y=(input())
print("coloque o numero 3")
z=(input())
print("coloque o numero 4")
a=(input())
diferenca=(x*y)-(z*a)
print("diferença =",diferenca)